### ISSUE TITLE
CC toolchain rules should only reference @rules_cc not @bazel_tools

### ISSUE THREAD

**Issue by nathaniel-brough** [bazelembedded/modular_cc_toolchains#4]
The modular toolchains proposal requires a change made to bazel here https://github.com/bazelbuild/bazel/pull/10967. This change has not yet been reflected in rules_cc although there is an open PR to merge this new functionality https://github.com/bazelbuild/rules_cc/pull/72.

**Comment by nathaniel-brough** [comment]
There are some other hitches, here as well, the action_config constructor in `@rules_cc` contains a `config_name` AND `action_name` this allows us to specify a name for the config seperate to the action_name. In `@bazel_tools` the action_config constructor does not have this config_name attribute which makes it impossible to specify relationships between actions and features.

So in short we need some of the features in `@bazel_tools` and some of the features in `@rules_cc` but we can't use both at the same time :(. So we really need https://github.com/bazelbuild/rules_cc/pull/72 to be merged before we continue.

**Comment by nathaniel-brough** [comment]
The current workaround I'm going with is to create an up-to-date fork of rules_cc that has the synced changes here https://github.com/silvergasp/rules_cc/tree/patch-2.

**Comment by tpudlik** [comment]
I'll see if I can get some more eyes on https://github.com/bazelbuild/rules_cc/pull/72.

**Comment by nathaniel-brough** [comment]
> I'll see if I can get some more eyes on https://github.com/bazelbuild/rules_cc/pull/72.

Thankyou!!
